## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Thu Oct 16 20:45:13 2025
## 
set sdc_version 1.4
current_design SYS_TOP
create_clock [get_ports {scan_clk}]  -name DFTCLK -period 10 -waveform {0 5}
set_clock_latency -min 0 [get_clocks {DFTCLK}]
set_clock_latency -max 0 [get_clocks {DFTCLK}]
set_clock_transition  -rise -min 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {DFTCLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {DFTCLK}]
create_clock [get_ports {UART_CLK}]  -name UART_CLK -period 271.296 -waveform {0 135.648}
set_clock_transition  -rise -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {UART_CLK}]
create_clock [get_ports {REF_CLK}]  -name REF_CLK -period 20 -waveform {0 10}
set_clock_transition  -rise -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {REF_CLK}]
create_generated_clock -name UART_RX_CLK -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {UART_CLK}] -add [get_pins {UART_RX_ClkDiv/U34/Y}]
create_generated_clock -name UART_TX_CLK -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {UART_CLK}] -add [get_pins {UART_TX_ClkDiv/U15/Y}]
create_generated_clock -name ALU_CLK -source [get_ports {REF_CLK}] -divide_by 1 -master_clock [get_clocks {REF_CLK}] -add [get_pins {U_CLK_GATE/U0_TLATNCAX12M/ECK}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_pins {UART_RX_ClkDiv/U34/Y}]
set_propagated_clock  [get_pins {UART_TX_ClkDiv/U15/Y}]
set_propagated_clock  [get_ports {scan_clk}]
set_propagated_clock  [get_ports {REF_CLK}]
set_propagated_clock  [get_pins {U_CLK_GATE/U0_TLATNCAX12M/ECK}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {test_mode}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_load -pin_load -max  0.1  [get_ports {SO[3]}]
set_load -pin_load -min  0.1  [get_ports {SO[3]}]
set_load -pin_load -max  0.1  [get_ports {SO[2]}]
set_load -pin_load -min  0.1  [get_ports {SO[2]}]
set_load -pin_load -max  0.1  [get_ports {SO[1]}]
set_load -pin_load -min  0.1  [get_ports {SO[1]}]
set_load -pin_load -max  0.1  [get_ports {SO[0]}]
set_load -pin_load -min  0.1  [get_ports {SO[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_load -pin_load -max  0.1  [get_ports {UART_TX_O}]
set_load -pin_load -min  0.1  [get_ports {UART_TX_O}]
set_load -pin_load -max  0.1  [get_ports {parity_error}]
set_load -pin_load -min  0.1  [get_ports {parity_error}]
set_load -pin_load -max  0.1  [get_ports {framing_error}]
set_load -pin_load -min  0.1  [get_ports {framing_error}]
set_case_analysis 0 [get_ports {SE}]
set_case_analysis 1 [get_ports {test_mode}]
set_input_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SI[3]}]
set_input_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SI[1]}]
set_input_delay -add_delay 54.2592 -clock [get_clocks {UART_RX_CLK}] [get_ports {UART_RX_IN}]
set_input_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SE}]
set_input_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {test_mode}]
set_input_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SI[2]}]
set_input_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SI[0]}]
set_output_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SO[2]}]
set_output_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SO[0]}]
set_output_delay -add_delay 1736.29 -clock [get_clocks {UART_TX_CLK}] [get_ports {UART_TX_O}]
set_output_delay -add_delay 54.2592 -clock [get_clocks {UART_RX_CLK}] [get_ports {parity_error}]
set_output_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SO[3]}]
set_output_delay -add_delay 2 -clock [get_clocks {DFTCLK}] [get_ports {SO[1]}]
set_output_delay -add_delay 54.2592 -clock [get_clocks {UART_RX_CLK}] [get_ports {framing_error}]
set_clock_uncertainty 0.1 -hold [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {ALU_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_TX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_TX_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {REF_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {REF_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_RX_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_RX_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {DFTCLK}]
set_clock_uncertainty 0.025 -setup [get_clocks {DFTCLK}]
set_clock_groups -name UART_CLK_1 -asynchronous  -group  [get_clocks {UART_TX_CLK UART_RX_CLK UART_CLK}] -group  [get_clocks {ALU_CLK REF_CLK}] -group  [get_clocks {DFTCLK}]
